### ISSUE TITLE
Fetching from DB kills the process and makes system unresponsive.

### ISSUE THREAD

**Issue by AaruBama** [PrimalHQ/primal-caching-service#19]
Hello Team,
Thank you so much for creating such a wonderful project.
It works well and fetches data correctly and dumps them into sqlite as expected but there are a few challenges I'm facing while trying to incorporate the system.

- In julia shell, whenever I try to call event stats: event_stats(Main.DB.CacheStorage(directory="path_to_db_folder", Main.Nostr.EventId("event_id"), it renders the system irrresponsive and after a while, shell closes automatically.
Can someone help me how should I query the database in the var folder and how can i use the exposed functions correctly?

**Comment by pritk** [comment]
for example, in julia REPL:
```
eid=Nostr.bech32_decode("note193krlw8navg52aetpmgsju5y4lcrcrp638gjdvmal7rfz6pacgmqnlh9qq")
App.event_stats(cache_storage, eid)
```
output:
```
1-element Vector{NamedTuple{(:kind, :content), Tuple{Int64, String}}}:
 (kind = 10000100, content = "{\"event_id\":\"2c6c3fb8f3eb1145772b0ed1097284aff03c0c3a89d126b37dff8691683dc236\",\"likes\":0,\"replies\":0,\"mentions\":0,\"reposts\":0,\"zaps\":0,\"satszapped\":0,\"score\":0,\"score24h\":0}")
```

**Comment by AaruBama** [comment]
Thank you. It worked. I was instantiating a DB.CacheStorage each time not knowing i could just use cache_storage directly. Your clarification and example worked smoothly. :bow: :+1: 

Just one more question before I can close it off. How are score and score_24h calculated. I tried reading julia but i keep moving in between functions due to my limited knowledge of jl.
Thanks.

**Comment by pritk** [comment]
that functionality is in different repo:

https://github.com/PrimalHQ/primal-server/blob/3094b8556423f54d98381efce8f4c5c6aa7f1e7e/ext/DB.jl#L482-L491
