### ISSUE TITLE
Not working on chrome with Alby

### ISSUE THREAD

**Issue by sarthak13gupta** [PrimalHQ/primal-caching-service#2]
I tried to explore primal.net on Chrome using Alby, but even after completing the actions of getPublicKey and the SignEvent, I'm not able to see any effect like I'm not able to post, follow, react, etc.
I have recorded it's working , please find it [here](https://drive.google.com/file/d/1U4VMAAEB8FVRpjFXIH5rRgkq9QIbvrTd/view?usp=sharing).

**Comment by mbrat1** [comment]
Thanks very much for the detailed report! 

We are aware of this issue and believe it has to do with connectivity to relays. We are currently working to solidify that code, as well as provide proper user feedback when there are relay connection issues. An improved build of the Primal web app should be ready in a few days.
