### ISSUE TITLE
Question: Is Primal the nostr client open source?

### ISSUE THREAD

**Issue by fr4nzap** [PrimalHQ/primal-caching-service#3]
If so, where is the repo?

Also: Can I report an issue or are you not interested in user feedback?

Apologies for posting here. On nostr my messages are being ignored.

**Comment by mbrat1** [comment]
Thank you for taking the time to reach out! Yes, we are definitely interested in user feedback, however we are not always able to catch all of it on nostr. 

To answer your question: our web client is not open source yet, but we are planing to open it in the next couple of weeks. Please stay tuned to our nostr account for the announcement. 

In the meantime, feel free to report any additional issues here.

**Comment by fr4nzap** [comment]
Appreciate your response and great news regarding open sourcing the client
