### ISSUE TITLE
Question: Does this store events in SQLite?

### ISSUE THREAD

**Issue by alexgleason** [PrimalHQ/primal-caching-service#8]
I'm trying to understand this code. I see SQLite being used. Is that really the main data store? You're indexing almost the entirety of Nostr with SQLite? If so, how?

**Comment by pritk** [comment]
> Is that really the main data store?

yes, sqlite is the main data store. all supported nostr events are imported into a number of sqlite DB files.

**Comment by alexgleason** [comment]
Thank you, very awesome design!
